#!/bin/bash
# Generate daily report as a Hexo blog post
# Reads Claude Code conversation history, filters sensitive info, outputs markdown

set -eo pipefail

BLOG_DIR="/workspace/blog"
POST_DIR="$BLOG_DIR/source/_posts"
TODAY=$(date +%Y-%m-%d)
POST_FILE="$POST_DIR/daily-report-$TODAY.md"

# Skip if today's report already exists
if [ -f "$POST_FILE" ]; then
  echo "Today's report already exists: $POST_FILE"
  exit 0
fi

# --- Sensitive info patterns to filter ---
sanitize() {
  sed -E \
    -e 's/ghp_[A-Za-z0-9]{36}/[GITHUB_TOKEN]/g' \
    -e 's/mk_[a-f0-9]{32}/[MAILS_API_KEY]/g' \
    -e 's/re_[A-Za-z0-9_]{20,}/[RESEND_API_KEY]/g' \
    -e 's/sk-[A-Za-z0-9]{20,}/[API_KEY]/g' \
    -e 's/Bearer [A-Za-z0-9_\-\.]{20,}/Bearer [REDACTED]/g' \
    -e 's/password["\x27: =]+[^ "\x27,}{]+/password=[REDACTED]/gi' \
    -e 's/secret["\x27: =]+[^ "\x27,}{]+/secret=[REDACTED]/gi' \
    -e 's/token["\x27: =]+[A-Za-z0-9_\-\.]{20,}/token=[REDACTED]/gi' \
    -e 's/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/[EMAIL]/g' \
    -e 's|https://github.com/users/[^/]+/emails/[^ ]*|[VERIFICATION_LINK]|g' \
    -e 's/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/[IP_ADDR]/g'
}

# --- Collect activity data ---

# Git activity today
GIT_LOG=""
for repo_dir in /workspace/*/; do
  if [ -d "$repo_dir/.git" ]; then
    repo_name=$(basename "$repo_dir")
    log=$(cd "$repo_dir" && git log --since="$TODAY" --oneline --no-merges 2>/dev/null || true)
    if [ -n "$log" ]; then
      GIT_LOG="$GIT_LOG\n### $repo_name\n\`\`\`\n$log\n\`\`\`\n"
    fi
  fi
done

# Claude conversation history (today's sessions)
HISTORY_DIR="$HOME/.claude"
CONVERSATION_SUMMARY=""
if [ -d "$HISTORY_DIR" ]; then
  # Check for projects directory with JSONL conversation files
  JSONL_FILES=$(find "$HISTORY_DIR" -name "*.jsonl" -newer "$HISTORY_DIR" -mtime 0 2>/dev/null | head -5 || true)
  if [ -n "$JSONL_FILES" ]; then
    CONVERSATION_SUMMARY="Found $(echo "$JSONL_FILES" | wc -l) active session(s) today."
  fi
fi

# Installed tools / environment changes
ENV_NOTES=""
if command -v mails &>/dev/null; then
  ENV_NOTES="$ENV_NOTES- mails CLI $(mails version 2>/dev/null || echo 'installed')\n"
fi
if command -v gh &>/dev/null; then
  ENV_NOTES="$ENV_NOTES- gh CLI $(gh --version 2>/dev/null | head -1)\n"
fi
if command -v hexo &>/dev/null; then
  ENV_NOTES="$ENV_NOTES- hexo CLI installed\n"
fi

# --- Generate post ---
mkdir -p "$POST_DIR"

cat > "$POST_FILE" << FRONTMATTER
---
title: "Daily Report - $TODAY"
date: $TODAY
tags:
  - daily-report
  - ai-agent
categories:
  - Daily Log
---

## Overview

Auto-generated daily report for **$TODAY** by Claude AI Agent (SentixA).

FRONTMATTER

# Git activity section
if [ -n "$GIT_LOG" ]; then
  echo -e "## Git Activity\n" >> "$POST_FILE"
  echo -e "$GIT_LOG" | sanitize >> "$POST_FILE"
else
  echo -e "## Git Activity\n\nNo git commits today.\n" >> "$POST_FILE"
fi

# Session summary
echo -e "\n## Session Summary\n" >> "$POST_FILE"
if [ -n "$CONVERSATION_SUMMARY" ]; then
  echo "$CONVERSATION_SUMMARY" | sanitize >> "$POST_FILE"
else
  echo "No conversation data available." >> "$POST_FILE"
fi

# Environment
if [ -n "$ENV_NOTES" ]; then
  echo -e "\n## Environment\n" >> "$POST_FILE"
  echo -e "$ENV_NOTES" | sanitize >> "$POST_FILE"
fi

echo -e "\n---\n\n*This report was auto-generated by [SentixA](https://github.com/sentixA) — a Claude AI Agent.*" >> "$POST_FILE"

echo "Generated: $POST_FILE"
